kind: pipeline
type: docker
name: Clean Build and Deploy

steps:
  - name: Clean
    image: mcr.microsoft.com/dotnet/sdk:latest
    commands:
      - dotnet clean DBProject_Drone_Demo.sln

  - name: Build
    image: mcr.microsoft.com/dotnet/core/sdk:latest
    commands:
      - dotnet build DBProject_Drone_Demo.sln
      
  - name: Deploy to Azure SQL Database 
    image: sijaymm/sqlpackage
    environment:
      SQL_SERVER_NAME:
        from_secret: SQL_SERVER_NAME
      DATABASE_NAME:
        from_secret: DATABASE_NAME
      USERNAME:
        from_secret: USERNAME
      PASSWORD:
        from_secret: PASSWORD
      SOURCE_FILE:
        from_secret: SOURCE_FILE
    commands:
      - sqlpackage /a:Publish /p:VerifyDeployment=True /p:CommandTimeout=0 /p:DatabaseServiceObjective=P2 /p:AllowIncompatiblePlatform=True /tsn:tcp:$SQL_SERVER_NAME /tdn:$DATABASE_NAME /tu:$USERNAME /tp:$PASSWORD /sf:/drone/src/DBProject_Drone_Demo.build/bin/Debug/netstandard2.0/DBProject_Drone_Demo.build.dacpac
      
      
trigger:
  branch:
    - master
    
    
    
    
