kind: pipeline
type: docker
name: Build, Backup and Deploy to Azure SQL Database

steps:
  - name: Clean
    image: mcr.microsoft.com/dotnet/sdk:latest
    commands:
      - dotnet clean DBProject_Drone_Demo.sln

  - name: Build
    image: mcr.microsoft.com/dotnet/core/sdk:latest
    commands:
      - dotnet build DBProject_Drone_Demo.sln
      
  - name: Backup Database
    image: mcr.microsoft.com/azure-cli
    environment:
      SQL_SERVER_NAME:
        from_secret: SQL_SERVER_NAME
      DATABASE_NAME:
        from_secret: DATABASE_NAME
      USERNAME:
        from_secret: USERNAME
      PASSWORD:
        from_secret: PASSWORD
      TENANT_ID:
        from_secret: TENANT_ID
      SERVICE_PRINCIPAL_USERNAME:
        from_secret: SERVICE_PRINCIPAL_USERNAME
      SERVICE_PRINCIPAL_PASSWORD:
        from_secret: SERVICE_PRINCIPAL_PASSWORD
      SERVICE_PRINCIPAL_PASSWORD:
        from_secret: SERVICE_PRINCIPAL_PASSWORD
      STORAGE_KEY:
        from_secret: STORAGE_KEY
      STORAGE_URI:
        from_secret: STORAGE_URI
    commands:
        - NOW=$(date +"%m-%d-%Y-%T")
        - FILE="droneDemo_$NOW.bacpac"
        - az login --service-principal -u $SERVICE_PRINCIPAL_USERNAME  -p $SERVICE_PRINCIPAL_PASSWORD --tenant $TENANT_ID
        - az sql db export -s drone-sql-demo -n $DATABASE_NAME -g My_Demo_RG -u $USERNAME -p $PASSWORD --storage-key $STORAGE_KEY --storage-key-type StorageAccessKey --storage-uri https://dronedemocontainer.blob.core.windows.net/drone-sql-export-demo/$FILE
      
      
  - name: Deploy to Azure SQL Database 
    image: sijaymm/sqlpackage
    environment:
      SQL_SERVER_NAME:
        from_secret: SQL_SERVER_NAME
      DATABASE_NAME:
        from_secret: DATABASE_NAME
      USERNAME:
        from_secret: USERNAME
      PASSWORD:
        from_secret: PASSWORD
    commands:
      - sqlpackage /a:Publish /p:VerifyDeployment=True /p:CommandTimeout=0 /p:DatabaseServiceObjective=P2 /p:AllowIncompatiblePlatform=True /tsn:tcp:$SQL_SERVER_NAME /tdn:$DATABASE_NAME /tu:$USERNAME /tp:$PASSWORD /sf:/drone/src/DBProject_Drone_Demo.build/bin/Debug/netstandard2.0/DBProject_Drone_Demo.build.dacpac
      
      
trigger:
  branch:
    - develop
    
    
    
    
    
    
    
