kind: pipeline
type: docker
name: Clean Build and Deploy

steps:     
  - name: Backup DB
    image: mcr.microsoft.com/azure-cli
    environment:
      SQL_SERVER_NAME:
        from_secret: SQL_SERVER_NAME
      RESOURCE_GROUP:
        from_secret: RESOURCE_GROUP
      DATABASE_NAME:
        from_secret: DATABASE_NAME
      USERNAME:
        from_secret: USERNAME
      PASSWORD:
        from_secret: PASSWORD
      SERVICE_PRINCIPAL_USERNAME:
        from_secret: SERVICE_PRINCIPAL_USERNAME
      SERVICE_PRINCIPAL_PASSWORD:
        from_secret: SERVICE_PRINCIPAL_PASSWORD
      SERVICE_PRINCIPAL_PASSWORD:
        from_secret: SERVICE_PRINCIPAL_PASSWORD
      TENANT_ID:
        from_secret: TENANT_ID
      TENANT_ID:
        from_secret: TENANT_ID
      STORAGE_KEY:
        from_secret: STORAGE_KEY
      STORAGE_URI:
        from_secret: STORAGE_URI
    commands:
        - az login --service-principal -u $SERVICE_PRINCIPAL_USERNAME  -p $SERVICE_PRINCIPAL_PASSWORD --tenant $TENANT_ID
        - az sql db export -s drone-sql-demo -n $DATABASE_NAME -g My_Demo_RG -p $PASSWORD -u $USERNAME --storage-key $STORAGE_KEY --storage-key-type StorageAccessKey --storage-uri https://dronedemo.blob.core.windows.net/drone-sql-export-demo/droneDemo.bacpac
      

trigger:
  branch:
    - master
    
    
    
