kind: pipeline
type: docker
name: Build, Backup and Deploy to Azure SQL Database

steps:
  - name: Clean
    image: rollersoftware/msbuild-windowsservercore
    commands:
      - dotnet clean DBProject_Drone_Demo.sln
      
      
trigger:
  branch:
    - develop
    
    
    
    
    
    
    
